services:
  postgres:
    image: postgres:16
    container_name: blog-strapi
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog-strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ~/.PostgressData/postgresonly/blog_strapi_api:/var/lib/postgresql/data/pgdata
    restart: always